make allure-results on root of the project

diff --git a/.github/workflows/selenium-grid-ci.yml b/.github/workflows/selenium-grid-ci.yml
--- a/.github/workflows/selenium-grid-ci.yml
+++ b/.github/workflows/selenium-grid-ci.yml
@@ -57,14 +57,14 @@ jobs:
 
       - name: 🕵️ Debug Allure Results Folder
         run: |
-          echo "Checking contents of target/allure-results:"
-          ls -l target/allure-results || echo "Folder not found"
+          echo "Checking contents of allure-results:"
+          ls -l allure-results || echo "Folder not found"
 
       - name: 📤 Upload Allure Results to Allure Server
         run: |
-          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
+          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
           echo "📦 Zipping Allure results..."
-          zip -r results.zip target/allure-results
+          zip -r results.zip allure-results
           echo "🚀 Uploading to Allure Server..."
           curl -X POST http://localhost:5050/send-results \
             -F "results=@results.zip" \
